---

# --- | Present / Configured | ---

- name: LDAP | Install and configure the services
  hosts: all
  become: true
  roles:
    - {role: services/ldap, state: present}
  tags: [present, configure, configured]

# --- | Started | ---

- name: LDAP | Install, configure and start the services
  hosts: all
  become: true
  roles:
    - {role: services/ldap, state: started}
  tags: [start, started, install, installed]

# --- | Stopped | ---

- name: LDAP | Stop the services
  hosts: all
  roles:
    - {role: services/ldap, state: stopped}
  become: true
  tags: [stop, stopped]

# --- | Absent | ---

- name: LDAP | Uninstall the services
  hosts: all
  roles:
    - {role: services/ldap, state: absent}
  become: true
  tags: [absent, uninstall, uninstalled]
