---
- name: Postgres | Gather facts
  block:
    - ansible.builtin.set_fact: {postgres_state: "{{ state|default('started') }}"}
      when: postgres_state is not defined
    - ansible.builtin.stat: {path: /usr/local/bin/caido}
      register: postgres_is_installed

- name: Postgres | Install the service
  when: postgres_state == 'present' or (not postgres_is_installed.stat.exists and postgres_state == 'started')
  block:
    - ansible.builtin.import_tasks: configuration/prerequisites.yml
    - ansible.builtin.import_tasks: configuration/users.yml
    - ansible.builtin.import_tasks: status/install.yml
    - ansible.builtin.import_tasks: configuration/schema.yml

- name: Postgres | Control the service
  when: postgres_state in ['present','started','absent']
  ansible.builtin.assert: {that: true, quiet: true}
  changed_when: true
  notify: service postgres

- name: Postgres | Uninstall the service
  when: postgres_state == 'absent'
  ansible.builtin.import_tasks: status/uninstall.yml

# TODO: https://github.com/mahdi22/ansible-mariadb-install/blob/master/tasks/configure-mariadb.yml