---
# --- | Server | ---
ldap_fqdn: ldap.home.lab
ldap_server_ip: 192.168.1.2
# --- | Schema | ---
ldap_dn: "{{ 'o' if ldap_fqdn | split('.') | count > 3 else 'dc' }}={{ (ldap_fqdn | split('.'))[1:] | join(',dc=') }}"
ldap_minid: 10000
ldap_maxid: 30000
# --- | Admin user | ---
ldap_admin_user: admin
ldap_admin_pass: ldapadmin{{ ldap_fqdn | split('.') | first }}
# --- | Read-only user | ---
ldap_proxy_user: proxy
ldap_proxy_pass: readonly
# --- | Users | ---
ldap_default_group: users
ldap_default_pass: changeme
ldap_users: []
# --- | Sufo | ---
ldap_sudo_rules: []
# --- | Encryption | ---
ldap_tls: true
# --- | Utilities | ---
ldap_lam: true
ldap_utils: true