---
# --- | Server | ---
ldap_server_ip: 192.168.1.2
ldap_server_hostname: cerberus
ldap_domain: "{{ homelab_domain|default('home.lab') }}"
# --- | Schema | ---
ldap_dn: "{{ 'o' if ldap_domain | split('.') | count > 2 else 'dc' }}={{ ldap_domain | split('.') | join(',dc=') }}"
ldap_minid: 10000
ldap_maxid: 30000
# --- | Users | ---
ldap_default_group: users
ldap_users: []
ldap_sudo_rules: []
# --- | Credentials | ---
ldap_admin_password: ldapadmin{{ ldap_domain | split('.') | first }}
ldap_default_password: changeme
ldap_proxy_password: readonly
# --- | Encryption | ---
ldap_tls: true
# --- | Utilities | ---
ldap_lam: true