---
ldap_admin_password: ldapadmin{{ ldap_domain | split('.') | first }}
ldap_default_password: changeme
ldap_domain: "{{ homelab_domain|default('home.lab') }}"
ldap_dn: "{{ 'o' if ldap_domain | split('.') | count > 2 else 'dc' }}={{ ldap_domain | split('.') | join(',dc=') }}"
ldap_minid: 10000
ldap_maxid: 30000
ldap_server_hostname: cerberus
ldap_server_ip: 192.168.1.2
ldap_lam: true
ldap_tls: true
ldap_users: []