# --- | Collection | ---

namespace: cosasdepuma
name: homelab
description: My own ready-to-use homelab galaxy
version: 0.0.1
homepage: https://lab.kike.wtf/
authors: [ Kike Fontan <@cosasdepuma> ]
tags: [ cosasdepuma, kikewtf, lab, homelab, selfhosted, galaxy ]

# --- | Repository | ---

readme: README.md
license_file: LICENSE
repository: https://github.com/kikewtf/galaxy
documentation: https://github.com/kikewtf/galaxy/blob/main/README.md
issues: https://github.com/kikewtf/galaxy/issues

# --- | Development | ---

dependencies: {}
build_ignore:
  # dev
  - .env
  - .old
  - .vscode
  # git
  - .git
  - .github
  - .gitignore
  # ansible
  - .tar.gz
  - group_vars
  - inventory.toml