- name: Proxmox | Templates - Download the templates
  block:
    - name: Proxmox | Templates - Ensure that ISO folder is created
      ansible.builtin.file:
        path: "{{ proxmox_isofolder }}"
        state: directory
        mode: 0700
        owner: root
        group: root
    
    - name: Proxmox | Templates - Download the templates
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ proxmox_isofolder }}/{{ item.name }}.qcow2"
        mode: 0400
        owner: root
        group: root
        checksum: "{{ item.checksum|default(omit) }}"
      with_items: "{{ proxmox_templates }}"

- name: Proxmox | Copy the SSH public key
  ansible.builtin.template:
    src: "{{ proxmox_default_sshkeyfile }}"
    dest: /tmp/ssh.pub
    mode: 0400
    owner: root
    group: root
  when: proxmox_default_sshkeyfile is defined and proxmox_default_sshkeyfile | length > 0
  register: proxmox_check_sshkey