---
- name: Proxmox | Machines - Control all the VMs
  community.general.proxmox_kvm:
    # status
    name: "{{ item['name'] }}"
    state: "{{ proxmox_machine_status }}"
    force: "{{ proxmox_machine_status == 'stopped' }}"
    # connection
    api_host: "{{ ansible_host }}"
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    node: "{{ ansible_hostname }}"
  with_items: "{{ proxmox_machines }}"