---
- name: Proxmox | Uninstall - Remove the VMs
  community.general.proxmox_kvm:
    # status
    name: "{{ item['name'] }}"
    state: absent
    force: true
    # connection
    api_host: "{{ ansible_host }}"
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    node: "{{ ansible_hostname }}"
  with_items: "{{ proxmox_machines }}"

- name: Proxmox | Uninstall - Remove the templates
  community.general.proxmox_kvm:
    # status
    name: "{{ item['name'] }}"
    state: absent
    # connection
    api_host: "{{ ansible_host }}"
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ ansible_password }}"
    node: "{{ ansible_hostname }}"
  with_items: "{{ proxmox_templates }}"

- name: Proxmox | Uninstall - Remove the ISOS
  ansible.builtin.file:
    path: "{{ proxmox_isofolder }}"
    state: absent