---
- name: MariaDB | Prerequisites - Install the dependecies
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-mysqldb
    - python3-openssl

- name: MariaDB | Prerequisites - Create the directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0750'
  with_items:
    - /var/log/mariadb
    - "{{ mariadb_data }}"
