---
- name: Postgres | Schema - Create the databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ postgres_databases }}"
  become: true
  become_user: postgres

- name: Postgres | Schema - Create the users
  community.postgresql.postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
  with_items: "{{ postgres_databases }}"
  become: true
  become_user: postgres

- name: Postgres | Schema - Grant the privileges
  community.postgresql.postgresql_privs:
    role: "{{ item.user }}"
    database: "{{ item.name }}"
    priv: ALL
    grant_option: false
    state: present
  with_items: "{{ postgres_databases }}"
  become: true
  become_user: postgres
