---
- name: LDAP | Install - Install the server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ldap-utils
    - openssl
    - slapd

- name: LDAP | Install - Ensure that the service is started and enabled
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: true
