---
- name: LDAP | Prerequisites - Install the prerequisites
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-cryptography
    - python3-ldap
