---
- name: LDAP | Properties - Configure server logging level
  community.general.ldap_attrs:
    dn: cn=config
    state: exact
    attributes:
      # 'stats' log connections/operations/results
      olcLogLevel: stats

- name: LDAP | Properties - Disable anonymous access
  community.general.ldap_attrs:
    dn: cn=config
    state: exact
    attributes:
      olcDisallows: bind_anon

- name: LDAP | Properties - Configure the server domain
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    state: exact
    attributes:
      olcSuffix: "{{ ldap_dn }}"

- name: LDAP | Properties - Configure the server admin account
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    state: exact
    attributes:
      olcRootDN: cn=admin,{{ ldap_dn}}
      olcRootPW: "{{ ldap_admin_password }}"