---
- name: MariaDB | Prerequisites - Install the dependecies
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-mysqldb
    - python3-openssl
