---
- name: LDAP | Server | LAM - Install the packages
  ansible.builtin.package:
    name: ldap-account-manager
    state: latest

- name: LDAP | Server | LAM - Configure the LAM service
  ansible.builtin.template:
    src: server/lam.conf.j2
    dest: /var/lib/ldap-account-manager/config/lam.conf
    owner: root
    group: root
    mode: 0644

- name: LDAP | Server | LAM - Remove default Apache installation files
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent
