---
- name: LDAP | Server | Utils - Install the packages
  ansible.builtin.package:
    name: ldap-utils
    state: latest

- name: LDAP | Server | Utils - Configure the LDAP client
  ansible.builtin.template:
    src: server/ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: 0644
