---
- name: LXC | Status - Control the containers
  community.general.proxmox:
    state: "{{ proxmox_status }}"
    vmid: "{{ item.vmid|default( item.ipv4.split('.')[-1] | int + proxmox_container_minid ) }}"
    # connection
    api_host: "{{ ansible_host }}"
    api_user: "{{ proxmox_admin_user }}"
    api_password: "{{ proxmox_admin_pass }}"
  with_items: "{{ proxmox_containers }}"