---
- name: LDAP | SSSD - Install the packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libnss-sss  # TODO: Make home directory on login
    - libpam-sss
    - libsss-sudo # TODO: Sudo permissions using SSSD
    - sssd
    - sssd-tools
    - sudo

- name: LDAP | SSSD - Configure the service
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: LDAP | SSSD - Remove fragmented configuration files
  ansible.builtin.file:
    path: /etc/sssd/conf.d
    state: absent

- name: LDAP | SSSD - Download server certificate
  ansible.builtin.shell:
    cmd: >
      openssl s_client
      -connect {{ [ldap_server_hostname,ldap_domain] | join('.') }}:636
      -showcerts </dev/null 2>/dev/null |
      openssl x509 -outform PEM > /etc/sssd/ldap.crt
    creates: /etc/sssd/ldap.crt
  when: ldap_tls

- name: LDAP | SSSD - Enable PAM MkHomeDir
  ansible.builtin.shell: >
    pam-auth-update
    --enable mkhomedir
  when: ansible_os_family | lower == 'debian'

- name: LDAP | SSSD - Restart the service
  ansible.builtin.service:
    name: sssd
    state: restarted
    enabled: true