---
- name: LDAP | Client | Uninstall - Remove the packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
      # ansible (management)
      - python3-cryptography
      # sssd (client)
      - libnss-sss
      - libpam-sss
      - libsss-sudo
      - sssd
      - sssd-tools

- name: LDAP | Client | Uninstall - Remove service files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    # sssd (client)
    - /etc/sssd
    - /var/lib/sssd
    - /var/log/sssd
    - /var/run/sssd.pid
