---
- name: Caido | Gather facts
  block:
    - ansible.builtin.set_fact: {caido_state: "{{ state|default('started') }}"}
      when: caido_state is not defined
    - ansible.builtin.stat: {path: /usr/local/bin/caido}
      register: caido_is_installed

- name: Caido | Install the service
  when: caido_state == 'present' or (not caido_is_installed.stat.exists and caido_state == 'started')
  block:
    - ansible.builtin.import_tasks: configuration/users.yml
    - ansible.builtin.import_tasks: status/install.yml

- name: Caido | Control the service
  when: caido_state in ['present','started','absent']
  ansible.builtin.assert: {that: true, quiet: true}
  changed_when: true
  notify: service caido

- name: Caido | Uninstall the service
  when: caido_state == 'absent'
  ansible.builtin.import_tasks: status/uninstall.yml
