---
- name: Caido | Service - Create the systemd service
  ansible.builtin.template:
    src: caido.service.j2
    dest: /etc/systemd/system/caido.service
    owner: root
    group: root
    mode: 0644
