---
- name: LDAP | Server | Uninstall - Remove the packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
    clean: true
    autoremove: true
  when: ansible_os_family | lower == 'debian'
  with_items:
    # ansible (management)
    - python3-cryptography
    - python3-ldap
    # ldap / slapd (server)
    - ldap-account-manager
    - ldap-utils
    - slapd

- name: LDAP | Server | Uninstall - Remove service files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    # ldap / slapd (server)
    - /etc/default/slapd
    - /etc/ldap
    - /var/backups
    - /var/lib/slapd
    - /var/lib/ldap
    - /var/run/slapd
    # sssd (client)
    - /etc/sssd
    - /var/lib/sssd
    - /var/log/sssd
    - /var/run/sssd.pid
