---
- name: LDAP | Clean - Stop the service
  ansible.builtin.service:
    name: slapd
    state: stopped
    enabled: false

- name: LDAP | Clean - Remove database folder
  ansible.builtin.file:
    path: /var/lib/ldap
    state: absent

- name: LDAP | Clean - Recreate database directory
  ansible.builtin.file:
    path: /var/lib/ldap
    state: directory
    mode: 0700
    owner: openldap
    group: openldap

- name: LDAP | Clean - Start the service
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: true
