---
- name: LDAP | Configure - Default DC
  community.general.ldap_entry:
    dn: "{{ ldap_dn }}"
    state: present
    objectClass: [top, dcObject, organization]
    attributes:
      dc: "{{ (ldap_fqdn | split('.'))[2] if ldap_fqdn | split('.') | count > 3 else (ldap_fqdn | split('.'))[1]  }}"
      o: "{{ (ldap_fqdn | split('.'))[1] if ldap_fqdn | split('.') | count > 3 else omit }}"
    # connection
    bind_dn: cn={{ ldap_admin_user }},{{ ldap_dn }}
    bind_pw: "{{ ldap_admin_pass }}"

- name: LDAP | Configure - Default OUs
  community.general.ldap_entry:
    dn: ou={{ item }},{{ ldap_dn }}
    state: present
    objectClass: [organizationalUnit]
    attributes:
      ou: "{{ item }}"
      description: "{{ item | title }} organizational unit"
    # connection
    bind_dn: cn={{ ldap_admin_user }},{{ ldap_dn }}
    bind_pw: "{{ ldap_admin_pass }}"
  with_items:
    - users
    - groups