---
- name: LDAP | Configure - Default System OU
  community.general.ldap_entry:
    dn: ou=system,{{ ldap_dn }}
    state: present
    objectClass: [organizationalUnit]
    attributes:
      ou: system
      description: System organizational unit
    # connection
    bind_dn: cn=admin,{{ ldap_dn }}
    bind_pw: "{{ ldap_admin_password }}"

- name: LDAP | Configure - Default Proxy Password
  ansible.builtin.shell: >
    /usr/sbin/slappasswd -s '{{ ldap_proxy_password }}'
  register: ldap_proxy_password_hash

- name: LDAP | Configure - Default Proxy User
  community.general.ldap_entry:
    dn: cn=proxy,ou=system,{{ ldap_dn }}
    state: present
    objectClass: [simpleSecurityObject, organizationalRole]
    attributes:
      cn: proxy
      userPassword: "{{ ldap_proxy_password_hash.stdout }}"
    # connection
    bind_dn: cn=admin,{{ ldap_dn }}
    bind_pw: "{{ ldap_admin_password }}"