---

# --- | Present | ---

- name: Loki | Install and/or stop the service
  hosts: loki
  become: true
  roles:
    - {role: services/ldap, state: present}
    - {role: services/duckdns, state: present}
  tags: [present]

# --- | Started | ---

- name: Loki | Install and/or start the service
  hosts: loki
  become: true
  roles:
    - {role: services/ldap, state: started}
    - {role: services/duckdns, state: started}
  tags: [start, started]

# --- | Absent | ---

- name: Loki | Uninstall the service
  hosts: loki
  roles:
    - {role: services/ldap, state: absent}
    - {role: services/duckdns, state: absent}
  become: true
  tags: [absent]
