---

# --- | Configure | ---

- name: Proxmox | Only create templates
  hosts: proxmox
  roles:
    - role: proxmox
      state: present
  become: yes
  tags: [ present, templates ]

# --- | Install | ---

- name: Proxmox | Install VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: configured
  become: yes
  tags: [ configure, configured, vms ]

# --- | Start | ---

- name: Proxmox | Start VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: started
  become: yes
  tags: [ start, started ]

# --- | Stop | ---

- name: Proxmox | Stop VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: stopped
  become: yes
  tags: [ stop, stopped ]

# --- | Clean | ---

- name: Proxmox | Uninstall VMs, templates and ISOs
  hosts: proxmox
  roles:
    - role: proxmox
      state: cleaned
  become: yes
  tags: [ clean, cleaned ]

# --- | Uninstall | ---

- name: Proxmox | Uninstall VMs, templates and ISOs
  hosts: proxmox
  roles:
    - role: proxmox
      state: absent
  become: yes
  tags: [ absent ]