---

# --- | Configure | ---

- name: Proxmox | Only create templates
  hosts: proxmox
  roles:
    - role: proxmox
      state: configured
  tags: [ configure, configured, download, downloaded, templates ]

# --- | Install | ---

- name: Proxmox | Install VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: present
  tags: [ create, created, deploy, deployed, install, installed, provision, provisioned ]

# --- | Start | ---

- name: Proxmox | Start VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: started
  tags: [ boot, booted, 'on', resume, resumed, start, started, up, vms ]

# --- | Stop | ---

- name: Proxmox | Stop VMs
  hosts: proxmox
  roles:
    - role: proxmox
      state: stopped
  tags: [ down, 'off', pause, paused, shutdown, stop, stopped ]

# --- | Clean | ---

- name: Proxmox | Uninstall VMs, templates and ISOs
  hosts: proxmox
  roles:
    - role: proxmox
      state: cleaned
  tags: [ clean, cleaned, delete, deleted, remove, removed ]

# --- | Uninstall | ---

- name: Proxmox | Uninstall VMs, templates and ISOs
  hosts: proxmox
  roles:
    - role: proxmox
      state: absent
  tags: [  prune, pruned, purge, purged, uninstall, uninstalled ]